# SentinOps Enterprise Hybrid Cloud Inventory
[all:vars]
ansible_user=sentinops_admin
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3

[linux_app_nodes]
host-linux-app-01 ansible_host=10.0.4.11 subnet=10.0.4.0/24 role=microservice
host-linux-app-02 ansible_host=10.0.4.12 subnet=10.0.4.0/24 role=microservice

[edge_gateways]
gw-edge-ingress-01 ansible_host=10.0.1.10 subnet=10.0.1.0/24 role=gateway_load_balancer

[db_clusters]
db-primary-rdbms ansible_host=10.0.5.20 subnet=10.0.5.0/24 role=postgresql_primary
db-nosql-telemetry ansible_host=10.0.5.21 subnet=10.0.5.0/24 role=mongodb_timeseries
db-graph-topology ansible_host=10.0.5.22 subnet=10.0.5.0/24 role=neo4j_graph

[bastion_hosts]
bastion-secure-01 ansible_host=10.0.0.5 subnet=10.0.0.0/24 role=bastion

[hybrid_cloud:children]
linux_app_nodes
edge_gateways
db_clusters
bastion_hosts
